MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
c_stdlib_version:          # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
lmdb:
  - 0.9.22
nodejs:
  - "18"
folly:
  - "2025.04.14.00"
xxhash:
  - 0.8.2
# State at:
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/424227d910b951bb7a2c78a2da401eb0e1f9e5fb/recipe/conda_build_config.yaml#L211-L236
aws_sdk_cpp:
  - 1.11.510
