{% set name = "arcticdb" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/man-group/ArcticDB/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 85b3bb3e853e4fcd855cd3edd8a2f50b5d16b2fdf0136553944b093ddaa3446a

build:
  # We skip the build on Windows because one of the dependencies (folly)
  # is not available for Windows on conda-forge
  # See: https://github.com/conda-forge/folly-feedstock/pull/98
  skip: true  # [win]
  number: 1

  entry_points:
    - arcticdb_update_storage = arcticdb.scripts.update_storage:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - python                                  # [build_platform != target_platform]
    - grpcio-tools                            # [build_platform != target_platform]
    - protobuf                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - libprotobuf <4                          # [build_platform != target_platform]
    - pkg-config                              # [build_platform != target_platform]
    - gnuconfig                               # [build_platform != target_platform]
  host:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
    - python
    - pip
    - folly
    - lz4-c
    - prometheus-cpp
    - double-conversion
    - libevent {{ libevent }}
    - libprotobuf <4
    - libmongocxx
    - zstd
    # TODO: pybind 2.11.X became stricter regarding the handling of reference counts
    # See: https://github.com/pybind/pybind11/issues/4748#issuecomment-1639445403
    # See: https://github.com/man-group/ArcticDB/pull/647
    - pybind11 <2.11
    - pcre
    - gflags
    - msgpack-c
    - aws-sdk-cpp
    - azure-core-cpp
    - azure-identity-cpp
    - azure-storage-blobs-cpp
    - bitmagic
    - xxhash
    - semimap
    - grpcio-tools
    - protobuf
    - spdlog
    - robin_hood
    - recycle
    - lmdb
    - lmdbxx
    - fmt
    - glog
    - gtest
  run:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
  # See install_requires: https://github.com/man-group/ArcticDB/blob/master/setup.cfg
    - glog
    - python
    # To keep in sync with `install_requires` in setup.cfg.
    - numpy
    - pandas <2
    - attrs
    - dataclasses # backport for Python < 3.7
    - decorator
    - grpcio-tools
    - python-xxhash
    - six
    - msgpack-python
    - psutil
    - pyyaml
    - decorator
    - prometheus_client
    # Resolves https://github.com/man-group/ArcticDB/issues/465
    - aws-crt-cpp >=0.19.8
    - prometheus-cpp
    - protobuf
    - lmdb
    - packaging
test:
  imports:
    - arcticdb

about:
  home: https://arcticdb.io/
  summary: ArcticDB is a high performance, serverless DataFrame database built for the Python Data Science ecosystem.
  description: |
    **ArcticDB** is a high performance, serverless **DataFrame database** built for
    the Python Data Science ecosystem. Launched in March 2023, it is the successor
    to [Arctic](https://github.com/man-group/arctic).
    ArcticDB offers an intuitive Python-centric API enabling you to read and write
    Pandas DataFrames to S3 or LMDB utilising a fast C++ data-processing and
    compression engine.
  license: BUSL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://docs.arcticdb.io
  dev_url: https://github.com/man-group/ArcticDB

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - jjerphan
    - mehertz
    - jamesmunro
    - qc00
    - willdealtry
    - poodlewars
    - vasil-pashov
    - GemDot
    - phoebusm
    - alexowens90
