{% set name = "arcticdb" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/man-group/ArcticDB/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 28f6f3f109b1cd0b02f40a9333c110aa252f61b3a7e5819229d56d774c6ae636

  patches:
  # When cross-compiling for apple-silicon, we absolutely need to make sure
  # that there is no hard-coded compiler in the cmake-preset / cmake-config.
  # While man-group/ArcticDB#662 is not merged,
  # we use a patch to remove the hard coded clang
    - patches/patch_compiler_for_darwin.patch 

build:
  # We skip the build on Windows because one of the dependencies (folly)
  # is not available for Windows on conda-forge
  # See: https://github.com/conda-forge/folly-feedstock/pull/98
  skip: true  # [win]
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - python                                  # [build_platform != target_platform]
    - grpcio-tools                            # [build_platform != target_platform]
    - protobuf                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - libprotobuf <4                          # [build_platform != target_platform]
    - pkg-config                              # [build_platform != target_platform]
    - gnuconfig                               # [build_platform != target_platform]
  host:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
    - python
    - pip
    - folly
    - lz4-c
    - prometheus-cpp
    - double-conversion
    - libevent {{ libevent }}
    - libprotobuf <4
    - libmongocxx
    - zstd
    # TODO: pybind 2.11.X became stricter regarding the handling of reference counts
    # See: https://github.com/pybind/pybind11/issues/4748#issuecomment-1639445403
    # See: https://github.com/man-group/ArcticDB/pull/647
    - pybind11 <2.11
    - pcre
    - gflags
    - cyrus-sasl =2.1.27
    - msgpack-c
    - aws-sdk-cpp
    - bitmagic
    - krb5 =1.20.1
    - xxhash
    - semimap
    - grpcio-tools
    - protobuf
    - spdlog
    - robin_hood
    - recycle
    - lmdb ==0.9.22
    - lmdbxx ==0.9.14
    - fmt <10
    - glog
    - gtest
  run:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
  # See install_requires: https://github.com/man-group/ArcticDB/blob/master/setup.cfg
    - glog
    - python
    # To keep in sync with `install_requires` in setup.cfg.
    - numpy
    - pandas <2
    - attrs
    - dataclasses # backport for Python < 3.7
    - decorator
    - grpcio-tools
    - python-xxhash
    - six
    - msgpack-python
    - psutil
    - pyyaml
    - decorator
    - prometheus_client
    # Required at runtime for their dynamically shared objects.
    # Pin to prevent errors such as:
    # E   ImportError: .../arcticdb_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: 
    # _ZNK5folly7futures6detail8CoreBase11getExecutorEv
    - folly ==2023.08.07.00
    # Resolves https://github.com/man-group/ArcticDB/issues/465
    - aws-crt-cpp >=0.19.8
    - prometheus-cpp
    - protobuf
    - lmdb
test:
  imports:
    - arcticdb

about:
  home: https://arcticdb.io/
  summary: ArcticDB is a high performance, serverless DataFrame database built for the Python Data Science ecosystem.
  description: |
    **ArcticDB** is a high performance, serverless **DataFrame database** built for
    the Python Data Science ecosystem. Launched in March 2023, it is the successor
    to [Arctic](https://github.com/man-group/arctic).
    ArcticDB offers an intuitive Python-centric API enabling you to read and write
    Pandas DataFrames to S3 or LMDB utilising a fast C++ data-processing and
    compression engine.
  license: BUSL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://docs.arcticdb.io
  dev_url: https://github.com/man-group/ArcticDB

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - jjerphan
    - mehertz
    - jamesmunro
    - qc00
    - willdealtry
    - poodlewars
    - vasil-pashov
    - GemDot
    - phoebusm
    - alexowens90
