{% set name = "arcticdb" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/man-group/ArcticDB/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 207b8951e4623bb2e87e0a3b3014ae12b7c4a696e7377b1910d9978dd1ad28eb

build:
  # We skip the build on Windows because of linkage problems with libprotobuf.
  # See: https://github.com/man-group/ArcticDB/pull/449
  skip: true  # [win]
  # The build of libprotobuf is lacking the _CFRelease symbol
  # Fixing requires to rebuild the whole stack while OSX build
  # for python 3.8 is not used  by anyone.
  skip: true  # [osx and py<39]
  number: 3

  entry_points:
    - arcticdb_update_storage = arcticdb.scripts.update_storage:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - python                                  # [build_platform != target_platform]
    - grpcio-tools                            # [build_platform != target_platform]
    - protobuf                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - libprotobuf                             # [build_platform != target_platform]
    - pkg-config                              # [build_platform != target_platform]
    - gnuconfig                               # [build_platform != target_platform]
  host:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
    - python
    - pip
    - folly
    - lz4-c
    - prometheus-cpp
    - double-conversion
    # See libevent variants' definition in `recipe/conda_build_config.yaml`
    - libevent
    - libprotobuf
    # TODO: Fix builds for missing symbols
    # See: https://github.com/man-group/ArcticDB/pull/1050
    - libmongocxx <3.9
    - zstd
    # TODO: pybind 2.11.X became stricter regarding the handling of reference counts
    # See: https://github.com/pybind/pybind11/issues/4748#issuecomment-1639445403
    # See: https://github.com/man-group/ArcticDB/pull/647
    - pybind11 <2.11
    - pcre
    - gflags
    - msgpack-c
    - aws-sdk-cpp
    - azure-core-cpp
    - azure-identity-cpp
    - azure-storage-blobs-cpp
    - bitmagic
    - xxhash
    - semimap
    - grpcio-tools
    - protobuf
    - spdlog
    - robin_hood
    - recycle
    # lmdb's version is constrained in `conda_build_config.yaml` because
    # specifying it here does not overide the conda-forge's global pinning.
    - lmdb
    - lmdbxx
    - fmt <10
    - glog
    - gtest
  run:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
  # See install_requires: https://github.com/man-group/ArcticDB/blob/master/setup.cfg
    - glog
    - python
    # To keep in sync with `install_requires` in setup.cfg.
    - numpy
    - pandas
    - attrs
    - dataclasses # backport for Python < 3.7
    - decorator
    - grpcio-tools
    - python-xxhash
    - six
    - msgpack-python
    - psutil
    - pyyaml
    - decorator
    - prometheus_client
    # Resolves https://github.com/man-group/ArcticDB/issues/465
    - aws-crt-cpp >=0.19.8
    - prometheus-cpp
    - protobuf
    - lmdb
    - packaging
    - pymongo
test:
  imports:
    - arcticdb

about:
  home: https://arcticdb.io/
  summary: ArcticDB is a high performance, serverless DataFrame database built for the Python Data Science ecosystem.
  description: |
    **ArcticDB** is a high performance, serverless **DataFrame database** built for
    the Python Data Science ecosystem. Launched in March 2023, it is the successor
    to [Arctic](https://github.com/man-group/arctic).
    ArcticDB offers an intuitive Python-centric API enabling you to read and write
    Pandas DataFrames to S3 or LMDB utilising a fast C++ data-processing and
    compression engine.
  license: BUSL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://docs.arcticdb.io
  dev_url: https://github.com/man-group/ArcticDB

extra:
  recipe-maintainers:
    - joe-iddon
    - G-D-Petrov
    - Hind-M
    - Klaim
    - JohanMabille
    - DerThorsten
    - jjerphan
    - mehertz
    - jamesmunro
    - qc00
    - willdealtry
    - poodlewars
    - vasil-pashov
    - phoebusm
    - alexowens90
