{% set name = "arcticdb" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/man-group/ArcticDB/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ede72b1a1f6430ce346f9374742643c217506f7034d801e02c38cdde18ec93d8
  patches:
    # TODO: remove this patch once this PR is merged
    # https://github.com/man-group/ArcticDB/pull/578
    - 0001-fix-Remove-uneeded-FMT_COMPILE.patch  # [linux]

build:
  # We skip the build on Windows because one of the dependencies (folly)
  # is not available for Windows on conda-forge
  # See: https://github.com/conda-forge/folly-feedstock/pull/98
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - python                                  # [build_platform != target_platform]
    - grpcio-tools                            # [build_platform != target_platform]
    - protobuf                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - libprotobuf <4                          # [build_platform != target_platform]
  host:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
    - python
    - pip
    - folly
    - lz4-c
    - prometheus-cpp
    - double-conversion
    - libevent {{ libevent }}
    - libprotobuf <4
    - libmongocxx
    - zstd
    - pybind11
    - pcre
    - gflags
    - cyrus-sasl =2.1.27
    - msgpack-c
    - aws-sdk-cpp
    - bitmagic
    - krb5 =1.20.1
    - xxhash
    - semimap
    - grpcio-tools
    - protobuf
    - spdlog
    - robin_hood
    - recycle
    - lmdb ==0.9.22
    - lmdbxx ==0.9.14
    - fmt <10
    - glog
    - gtest
  run:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
  # See install_requires: https://github.com/man-group/ArcticDB/blob/master/setup.cfg
    - glog
    - python
    # To keep in sync with `install_requires` in setup.cfg.
    - numpy
    - pandas <2
    - attrs
    - dataclasses # backport for Python < 3.7
    - decorator
    - grpcio-tools
    - python-xxhash
    - six
    - msgpack-python
    - psutil
    - pyyaml
    - decorator
    - prometheus_client
    # Required at runtime for their dynamically shared objects.
    - folly
    # Resolves https://github.com/man-group/ArcticDB/issues/465
    - aws-crt-cpp >=0.19.8
    - prometheus-cpp
    - protobuf
    - lmdb
test:
  imports:
    - arcticdb

about:
  home: https://arcticdb.io/
  summary: ArcticDB is a high performance, serverless DataFrame database built for the Python Data Science ecosystem.
  description: |
    **ArcticDB** is a high performance, serverless **DataFrame database** built for
    the Python Data Science ecosystem. Launched in March 2023, it is the successor
    to [Arctic](https://github.com/man-group/arctic).
    ArcticDB offers an intuitive Python-centric API enabling you to read and write
    Pandas DataFrames to S3 or LMDB utilising a fast C++ data-processing and
    compression engine.
  license: BUSL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://docs.arcticdb.io
  dev_url: https://github.com/man-group/ArcticDB

extra:
  recipe-maintainers:
    - DerThorsten
    - jjerphan
    - mehertz
    - jamesmunro
    - qc00
    - willdealtry
    - poodlewars
    - vasil-pashov
    - GemDot
    - phoebusm
    - alexowens90
