{% set name = "arcticdb" %}
{% set version = "4.4.3rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/man-group/ArcticDB/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 39f41487024eb0ed64b23c1adcc0305523aa106758ad3acacfb68fec00d97d53
  patches:
    - patches/0001-Skip-pyarrow.patch

build:
  # We skip the build on Windows because of linkage problems with libprotobuf.
  # See: https://github.com/man-group/ArcticDB/pull/449
  skip: true  # [win]
  # The build of libprotobuf is lacking the _CFRelease symbol
  # Fixing requires to rebuild the whole stack while OSX build
  # for python 3.8 is not used  by anyone.
  skip: true  # [osx and py<39]
  # not ready yet; needs to unpin pybind11
  skip: true  # [py>=312]
  number: 0

  entry_points:
    - arcticdb_update_storage = arcticdb.scripts.update_storage:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - python                                  # [build_platform != target_platform]
    - numpy                                   # [build_platform != target_platform]
    - grpcio-tools                            # [build_platform != target_platform]
    - protobuf                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - libprotobuf <4                          # [build_platform != target_platform]
    - pkg-config                              # [build_platform != target_platform]
    - gnuconfig                               # [build_platform != target_platform]
  host:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
    - python
    - numpy
    - pip
    - folly
    - lz4-c
    - prometheus-cpp
    - double-conversion
    # See libevent variants' definition in `recipe/conda_build_config.yaml`
    - libevent
    - libprotobuf <4
    - openssl
    - libcurl
    # TODO: Fix builds for missing symbols
    # See: https://github.com/man-group/ArcticDB/pull/1050
    - libmongocxx <3.9
    - zstd
    # TODO: pybind 2.11.X became stricter regarding the handling of reference counts
    # See: https://github.com/pybind/pybind11/issues/4748#issuecomment-1639445403
    # See: https://github.com/man-group/ArcticDB/pull/647
    - pybind11 <2.11
    - pcre
    - gflags
    - msgpack-c
    - aws-sdk-cpp
    - azure-core-cpp
    - azure-identity-cpp
    - azure-storage-blobs-cpp
    - bitmagic
    - xxhash
    - semimap
    - grpcio-tools
    - protobuf
    - spdlog
    - unordered_dense
    - recycle
    # lmdb's version is constrained in `conda_build_config.yaml` because
    # specifying it here does not overide the conda-forge's global pinning.
    - lmdb
    - lmdbxx
    - fmt
    - glog
    - gtest
    - benchmark
  run:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
  # See install_requires: https://github.com/man-group/ArcticDB/blob/master/setup.cfg
    - glog
    - python
    # To keep in sync with `install_requires` in setup.cfg.
    # Enforce the same major NumPy version at runtime.
    # See: https://conda-forge.org/docs/maintainer/knowledge_base/#building-against-numpy
    - {{ pin_compatible('numpy') }}
    - pandas
    - attrs
    - decorator
    - msgpack-python
    - psutil
    - pyyaml
    # Resolves https://github.com/man-group/ArcticDB/issues/465
    - aws-crt-cpp >=0.19.8
    - prometheus-cpp
    - protobuf >=3.5.1, <5
    - lmdb
    - packaging
test:
  requires:
  # This environment specification must be maintained in sync with the one upstream:
  # See: https://github.com/man-group/ArcticDB/blob/master/environment_unix.yml
  # See `options.extras_require`: https://github.com/man-group/ArcticDB/blob/master/setup.cfg
    - pytest
    # We disable pyarrow because the environement is too constrained.
    # Only one test is skipped via the patch applied above.
    # - pyarrow
    - pytest-cpp
    - pytest-timeout
    - pytest-xdist
    - packaging
    - future
    - mock
    - boto3
    - moto
    - flask  # Used by moto
    - flask-cors
    - hypothesis <6.73
    - azure-storage-blob
    - azure-identity
    - coverage
    - asv
    - virtualenv
    - pymongo
    - mock
  # Extra dependencies
    - pytest-rerunfailures
    - nodejs  # for npm
  source_files:
    - python/tests
  imports:
    - arcticdb
  commands:
    - npm install -g azurite
    # Skip slow tests, which includes the ones for MongoDB and Azure Blob Storage
    # See: https://github.com/conda-forge/arcticdb-feedstock/issues/151
    # See: https://github.com/conda-forge/arcticdb-feedstock/issues/152
    - export ARCTICDB_FAST_TESTS_ONLY=1
    # Machines have 2 CPUs, we retry in case of failure to be sure all configurations' builds are published.
    #
    # For now, we skip the following tests:
    #  - Tests for Azure are deactivated for now (not present for MacOS, fails for Linux).
    #  - `test_lmdb_warnings_when_reopened` also currently fails.
    - ARCTICDB_RAND_SEED=$RANDOM pytest python/tests --verbose -n 2 --reruns 5 --reruns-delay 1 -k "not Azure and not azurite and not test_lmdb_warnings_when_reopened"

about:
  home: https://arcticdb.io/
  summary: ArcticDB is a high performance, serverless DataFrame database built for the Python Data Science ecosystem.
  description: |
    **ArcticDB** is a high performance, serverless **DataFrame database** built for
    the Python Data Science ecosystem. Launched in March 2023, it is the successor
    to [Arctic](https://github.com/man-group/arctic).
    ArcticDB offers an intuitive Python-centric API enabling you to read and write
    Pandas DataFrames to S3 or LMDB utilising a fast C++ data-processing and
    compression engine.
  license: BUSL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://docs.arcticdb.io
  dev_url: https://github.com/man-group/ArcticDB

extra:
  recipe-maintainers:
    - joe-iddon
    - G-D-Petrov
    - Hind-M
    - Klaim
    - JohanMabille
    - DerThorsten
    - jjerphan
    - mehertz
    - jamesmunro
    - qc00
    - willdealtry
    - poodlewars
    - vasil-pashov
    - phoebusm
    - alexowens90
