build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
bot:
  abi_migration_branches:
    - rc
    - libevent-2.1.10
