bot:
  abi_migration_branches:
  - rc
  - 5.1.x
  - 5.2.x
build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
conda_install_tool: pixi
conda_build_tool: rattler-build
